<template>
  <div class="c-delivery-note">
    <!-- Header Section -->
    <div class="bg-gray-700 p-4 mb-6">
      <h2 class="text-2xl text-white my-2">Date: {{ currentDate }}</h2>
      <h2 class="text-2xl text-white my-2">
        Delivery Note No.: {{ deliveryNoteNumber }}
      </h2>
      <h2 class="text-2xl text-white my-2">Generated by: John Doe</h2>
    </div>

    <!-- Summary Section -->
    <div class="c-delivery-summary">
      <!-- Table Header -->
      <div class="flex justify-between bg-slate-700 p-6 my-2 text-slate-200">
        <div class="w-1/6 text-center">S.No</div>
        <div class="w-1/6 text-center">Product</div>
        <div class="w-1/6 text-center">Cost Price</div>
        <div class="w-1/6 text-center">Selling Price</div>
        <div class="w-1/6 text-center">Quantity</div>
        <div class="w-1/6 text-center">Total Amount</div>
      </div>

      <!-- Hardcoded Items -->
      <div
        class="flex justify-between items-center p-6 border-b-2 gap-x-2"
        v-for="(row, index) in hardcodedRows"
        :key="index"
      >
        <div class="w-1/6 text-center">{{ index + 1 }}</div>
        <div class="w-1/6 text-center">{{ row.product }}</div>
        <div class="w-1/6 text-center">{{ row.costPrice }} Dhs</div>
        <div class="w-1/6 text-center">{{ row.sellingPrice }} Dhs</div>
        <div class="w-1/6 text-center">{{ row.quantity }}</div>
        <div class="w-1/6 text-center">
          {{ row.sellingPrice * row.quantity }} Dhs
        </div>
      </div>

      <!-- Subtotal Row -->
      <div class="flex justify-between bg-slate-700 p-6 my-2 text-slate-200">
        <div class="w-5/6 text-right font-bold">Subtotal:</div>
        <div class="w-1/6 text-center">{{ subtotal }} Dhs</div>
      </div>
    </div>
    <!-- Print Button -->
    <div class="flex justify-center my-4">
      <button
        @click="printPage"
        class="bg-blue-500 text-white px-4 py-2 rounded-lg"
      >
        Print Delivery Note
      </button>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      // Current Date
      currentDate: new Date().toLocaleDateString(),

      // Random Delivery Note Number
      deliveryNoteNumber: Math.floor(100000 + Math.random() * 900000),

      // Hardcoded rows (for now)
      hardcodedRows: [
        { product: "Product A", costPrice: 50, sellingPrice: 80, quantity: 2 },
        { product: "Product B", costPrice: 40, sellingPrice: 70, quantity: 1 },
        { product: "Product C", costPrice: 30, sellingPrice: 60, quantity: 3 },
      ],
    };
  },

  computed: {
    // Calculate subtotal
    subtotal() {
      return this.hardcodedRows.reduce((acc, row) => {
        return acc + row.sellingPrice * row.quantity;
      }, 0);
    },
  },
  methods: {
    printPage() {
      const self = this;
      window.print();
    },
  },
};
</script>

<style scoped>
.c-delivery-note {
  width: 90%;
  margin: 0 auto;
}

.c-delivery-summary {
  margin-top: 20px;
}

.bg-gray-200 {
  background-color: #e2e8f0;
}

.text-slate-200 {
  color: #e2e8f0;
}

.bg-slate-700 {
  background-color: #2d3748;
}

/* Print-specific styles */
@media print {
  .bg-gray-200 {
    background-color: #e2e8f0 !important;
  }

  .text-slate-200 {
    color: #e2e8f0 !important;
  }

  .bg-slate-700 {
    background-color: #2d3748 !important;
  }

  /* Force the print button to be hidden when printing */
  button {
    display: none;
  }
}
</style>
