<template>
  <div class="c-delivery-note">
    <template v-if="!isLoading">
      <!-- Header Section -->
      <div class="bg-gray-700 p-4 mb-6">
        <h2 class="text-2xl text-slate-200 my-2 text-red">
          Date: {{ getFormattedDate(deliveryDetails.date) }}
        </h2>
        <h2 class="text-2xl text-white my-2" v-if="deliveryDetails">
          Delivery Note No.: {{ deliveryDetails._id }}
        </h2>
        <h2 class="text-2xl text-white my-2">Generated by: John Doe</h2>
      </div>

      <!-- Summary Section -->
      <div class="c-delivery-summary">
        <!-- Table Header -->
        <div class="flex justify-between bg-slate-700 p-6 my-2 text-slate-200">
          <div class="w-1/6 text-center">S.No</div>
          <div class="w-1/6 text-center">Product</div>
          <div class="w-1/6 text-center">Cost Price</div>
          <div class="w-1/6 text-center">Selling Price</div>
          <div class="w-1/6 text-center">Quantity</div>
          <div class="w-1/6 text-center">Total Amount</div>
        </div>

        <!-- Hardcoded Items -->
        <div
          class="flex justify-between items-center p-6 border-b-2 gap-x-2"
          v-for="(product, index) in products"
          :key="index"
        >
          <div class="w-1/6 text-center">{{ index + 1 }}</div>
          <div class="w-1/6 text-center">{{ product.product_name }}</div>
          <div class="w-1/6 text-center">{{ product.cost_price }} Dhs</div>
          <div class="w-1/6 text-center">{{ product.selling_price }} Dhs</div>
          <div class="w-1/6 text-center">{{ product.quantity }}</div>
          <div class="w-1/6 text-center">
            {{ product.selling_price * product.quantity }} Dhs
          </div>
        </div>

        <!-- Subtotal Row -->
        <div class="flex justify-between bg-slate-700 p-6 my-2 text-slate-200">
          <div class="w-5/6 text-right font-bold">Subtotal:</div>
          <div class="w-1/6 text-center">{{ subtotal }} Dhs</div>
        </div>
      </div>
      <!-- Print Button -->
      <div class="flex justify-center my-4">
        <button
          @click="printPage"
          class="bg-blue-500 text-white px-4 py-2 rounded-lg"
        >
          Print Delivery Note
        </button>
      </div>
    </template>
    <template v-else>
      <h1>Loading...</h1>
    </template>
  </div>
</template>

<script>
import { apiUtilsService } from "../../services/apiUtilsService";

export default {
  data() {
    return {
      // Current Date
      currentDate: new Date().toLocaleDateString(),
      isLoading: false,
      deliveryDetails: null,
    };
  },

  computed: {
    // Calculate subtotal
    subtotal() {
      const self = this;
      return self.products.reduce((acc, product) => {
        return acc + product.selling_price * product.quantity;
      }, 0);
    },
    products() {
      const self = this;
      return (self.deliveryDetails && self.deliveryDetails.products) || [];
    },
  },
  created() {
    const self = this;
    self.initialize();
  },
  methods: {
    initialize() {
      const self = this;
      self.getDeliveryDetails();
    },
    getDeliveryDetails() {
      const self = this;
      const deliveryNoteId = self.$route.params.id;
      self.isLoading = true;
      apiUtilsService
        .getDeliveryNoteDetails(deliveryNoteId)
        .then((res) => {
          if (res.status === "success") {
            self.deliveryDetails = res.data;
          }
        })
        .catch((err) => {
          console.log(err);
        })
        .finally(() => {
          self.isLoading = false;
        });
    },
    printPage() {
      window.print();
    },
    getFormattedDate(date) {
      const self = this;
      return new Date(date).toLocaleDateString();
    },
  },
};
</script>

<style scoped></style>
